### PR TITLE
Issue#2 with savestate

### PR DESCRIPTION
**Pull request by ghost**
This is the result with an 80 ton allowance and negotiated for all salvage (negative cbill outcome as a result).

It was saved and loaded a few times so that part is working.

image

### CODE REVIEW

**Comment by Morphyum** [comment]
I havent forgotten you, sorry it takes so long, having some slight health problems right now, so dont feel like testing, but i promise before i start work on another mod i will test this first.

**Comment by ghost** [comment]
I appreciate the reply I was honestly wondering a bit.  I hope you feel
better soon, no rush on the mods, just a hobby for me, health first!

**Comment by Morphyum** [comment]
Looks good so far gonna merge it and test it as soon as i get home.

**Comment by ghost** [comment]
Woo!  thanks Morphyum

**Comment by Morphyum** [comment]
i thank you for delivering people that want this feature :)

**Pull request merged**
