### PR TITLE
Issue#2

### PR DESCRIPTION
**Pull request by ghost**
I tested it with freeTonnageAmount values less than and exceeding the drop tonnage and the lowest cost will be 0, while the highest is unconstrained as before.

### CODE REVIEW

**Comment by ghost** [comment]
I'm going to sleep!  I think this is ready to merge.

**Comment by ghost** [comment]
image

**Comment by Morphyum** [comment]
Have to think about this, also i changed a lot of code that i will push soon

**Comment by Morphyum** [comment]
Yea cant pull this anymore since it would break the savestate i just implemented, please provide a fixed pull

**Comment by ghost** [comment]
Will do/try

**Pull request closed without merging**
